CATALOG_MEDIA = {
    "pestañas": {
        "title": "Pestañas",
        "category": "beauty",
        "keywords": ["pestaña", "pestañas", "lash", "lashes"],
        "image": "prices/PromoPestanas350.jpeg",
        "caption": "✨ Promoción vigente en pestañas\nPrecio regular $500\nPor tiempo limitado: $350\nAnticipo: $150",
        "price": 350,
        "regular_price": 500,
        "deposit": 150,
        "duration_minutes": 120,
        "enabled": True,
    },
    "uñas": {
        "title": "Uñas",
        "category": "beauty",
        "keywords": ["uña", "uñas", "nail", "nails", "gel", "gelish", "semipermanente", "acrilico", "acrílico"],
        "image": "prices/Gelish01.jpeg",
        "caption": "💅 Servicios de uñas\nGelish/Gel desde $120\nAcrílicas desde $250\nAnticipo: $150",
        "price": 120,
        "deposit": 150,
        "duration_minutes": 120,
        "enabled": True,
    },
}
